#!/bin/bash

. /etc/profile 2>/dev/null || true

INSTALLER_VERSION="v2"

if [ "$(id -u)" != "0" ]; then
  echo "Run this installer as root"
  exit 1
fi

if [ "$(uname -m)" != "aarch64" ]; then
  echo "This installer supports ARM64 ROCKNIX devices"
  exit 1
fi

for CANDIDATE in /storage/.config/drastic /root/.config/drastic; do
  if [ -e "$CANDIDATE/drastic" ] || [ -e "$CANDIDATE/drastic.bin" ]; then
    DRASTIC_DIR="$CANDIDATE"
    break
  fi
done

if [ -z "$DRASTIC_DIR" ]; then
  echo "DraStic installation was not found"
  exit 1
fi

DRASTIC_LAUNCHER="$DRASTIC_DIR/drastic"
DRASTIC_BINARY="$DRASTIC_DIR/drastic.bin"
MENU_LIBRARY="$DRASTIC_DIR/librgdsmenu.so"
SWAY_CONFIG="/storage/.config/sway/config"
SWAP_SCRIPT="/roms/ports/Swap RGDS Screens.sh"

if [ ! -x "$DRASTIC_BINARY" ]; then
  if file "$DRASTIC_LAUNCHER" | grep -q 'ELF'; then
    mv "$DRASTIC_LAUNCHER" "$DRASTIC_BINARY"
  else
    echo "Native DraStic binary was not found"
    exit 1
  fi
fi

PAYLOAD_LINE=$(awk '/^__MENU_LIBRARY__$/ { print NR + 1; exit }' "$0")
if [ -z "$PAYLOAD_LINE" ]; then
  echo "Embedded menu library is missing"
  exit 1
fi

tail -n "+$PAYLOAD_LINE" "$0" | base64 -d > "$MENU_LIBRARY.tmp" || {
  rm -f "$MENU_LIBRARY.tmp"
  echo "Unable to extract the embedded menu library"
  exit 1
}

if ! file "$MENU_LIBRARY.tmp" | grep -q 'ELF 64-bit.*ARM aarch64'; then
  rm -f "$MENU_LIBRARY.tmp"
  echo "Embedded menu library failed validation"
  exit 1
fi

chmod 755 "$MENU_LIBRARY.tmp"
mv "$MENU_LIBRARY.tmp" "$MENU_LIBRARY"

TOUCH_LIBRARY=""
for CANDIDATE in /usr/lib/libdrastouch.so /usr/lib64/libdrastouch.so; do
  if [ -f "$CANDIDATE" ]; then
    TOUCH_LIBRARY="$CANDIDATE:"
    break
  fi
done

cat > "$DRASTIC_LAUNCHER.tmp" <<EOF
#!/bin/bash

export SDL_VIDEO_WAYLAND_WMCLASS="drastic"
export LD_PRELOAD="${TOUCH_LIBRARY}${MENU_LIBRARY}"
exec "$DRASTIC_BINARY" "\$@"
EOF

chmod 755 "$DRASTIC_LAUNCHER.tmp"
mv "$DRASTIC_LAUNCHER.tmp" "$DRASTIC_LAUNCHER"

if [ -f "$SWAY_CONFIG" ]; then
  TOP_OUTPUT="DSI-2"
  BOTTOM_OUTPUT="DSI-1"
  TOUCH_IDENTIFIER=""

  if command -v swaymsg >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    OUTPUTS=$(swaymsg -t get_outputs 2>/dev/null | jq -r '.[].name' 2>/dev/null)
    if ! printf '%s\n' "$OUTPUTS" | grep -qx "$TOP_OUTPUT"; then
      TOP_OUTPUT=$(printf '%s\n' "$OUTPUTS" | sed -n '1p')
      BOTTOM_OUTPUT=$(printf '%s\n' "$OUTPUTS" | sed -n '2p')
    fi
    TOUCH_IDENTIFIER=$(swaymsg -t get_inputs 2>/dev/null \
      | jq -r '.[] | select(.type == "touch") | .identifier' 2>/dev/null \
      | head -n 1)
  fi

  RULE="for_window [app_id=\"drastic\"] border none, move absolute position 0 0"
  if [ -n "$BOTTOM_OUTPUT" ]; then
    RULE="$RULE, output $BOTTOM_OUTPUT power on"
  fi
  if [ -n "$TOP_OUTPUT" ]; then
    RULE="$RULE, output $TOP_OUTPUT power on, focus"
  fi
  if [ -n "$TOUCH_IDENTIFIER" ] && [ -n "$TOP_OUTPUT" ]; then
    RULE="$RULE, input \"$TOUCH_IDENTIFIER\" map_to_output $TOP_OUTPUT"
  fi
  if [ -x "$SWAP_SCRIPT" ]; then
    RULE="$RULE, exec /bin/bash \"$SWAP_SCRIPT\" --watch-drastic"
  fi

  awk -v rule="$RULE" '
    BEGIN { replaced = 0 }
    /^for_window \[app_id=".*drastic.*"\]/ {
      if (!replaced) print rule
      replaced = 1
      next
    }
    { print }
    END { if (!replaced) print rule }
  ' "$SWAY_CONFIG" > "$SWAY_CONFIG.tmp"
  mv "$SWAY_CONFIG.tmp" "$SWAY_CONFIG"

  if [ -n "$BOTTOM_OUTPUT" ]; then
    sed -i "/^output $BOTTOM_OUTPUT bg /d" "$SWAY_CONFIG"
    printf 'output %s bg #000000 solid_color\n' "$BOTTOM_OUTPUT" >> "$SWAY_CONFIG"
  fi

  swaymsg reload >/dev/null 2>&1 || true
fi

sync
echo "DraStic 1.5x top-screen menu installed ($INSTALLER_VERSION)"
exit 0

__MENU_LIBRARY__
f0VMRgIBAQAAAAAAAAAAAAMAtwABAAAAAAAAAAAAAABAAAAAAAAAAGgJAAAAAAAAAAAAAEAAOAAJ
AEAAEQAQAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA+AEAAAAAAAD4AQAAAAAAAAgA
AAAAAAAAAQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBQAAAAAAAAQFAAAAAAAAAAAB
AAAAAAABAAAABQAAAAQFAAAAAAAABAUBAAAAAAAEBQEAAAAAAKwCAAAAAAAArAIAAAAAAAAAAAEA
AAAAAAEAAAAGAAAAsAcAAAAAAACwBwIAAAAAALAHAgAAAAAAAAEAAAAAAABQCAAAAAAAAAAAAQAA
AAAAAQAAAAYAAACwCAAAAAAAALAIAwAAAAAAsAgDAAAAAAAAAAAAAAAAACgAAAAAAAAAAAABAAAA
AAACAAAABgAAALAHAAAAAAAAsAcCAAAAAACwBwIAAAAAAOAAAAAAAAAA4AAAAAAAAAAIAAAAAAAA
AFLldGQEAAAAsAcAAAAAAACwBwIAAAAAALAHAgAAAAAAAAEAAAAAAABQCAAAAAAAAAEAAAAAAAAA
UOV0ZAQAAAAUBAAAAAAAABQEAAAAAAAAFAQAAAAAAAAkAAAAAAAAACQAAAAAAAAABAAAAAAAAABR
5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAASAAkABAUB
AAAAAABsAAAAAAAAABoAAAASAAkAcAUBAAAAAACcAAAAAAAAACwAAAASAAkADAYBAAAAAABwAQAA
AAAAAAEAAAACAAAAAQAAABoAAABEAkAABAAEAAIAAADyGNhYBu8NCqMGcScFAAAABQAAAAMAAAAA
AAAAAgAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAU0RMX0NyZWF0ZVJlbmRlcmVyAGRs
c3ltAFNETF9TZXRXaW5kb3dTaXplAFNETF9SZW5kZXJDb3B5AGxpYnJnZHNtZW51LnNvAAAAAAAA
AKgIAgAAAAAAAgQAAAEAAAAAAAAAAAAAAIACAAADAAAAAAAAAAAAAADbuV4mAQAAgNu5XiYBAACA
AAAAAAAAAACAAgAA4AEAAB4AAABQAAAAqwEAAEABAAAAAAAAAAAAAIACAAADAAAA+v///wAAAAD6
////AAAAAAC1//8Q////AAAAAAAAAABTRExfUmVuZGVyQ29weQBTRExfQ3JlYXRlUmVuZGVyZXIA
U0RMX1NldFdpbmRvd1NpemUAARsDOyAAAAADAAAA8AABADgAAABcAQEAbAAAAPgBAQCgAAAAEAAA
AAAAAAABelIAAXweARsMHwAwAAAAGAAAALAAAQBsAAAAAEQOMEwMHTCTApQElQaWCJ4KnQwCTAwf
MEwOANPU1dbe3QAAMAAAAEwAAADoAAEAnAAAAABEDjBMDB0wkwKUBJUGlgieCp0MAnwMHzBMDgDT
1NXW3t0AAEgAAACAAAAAUAEBAHABAAAARA5gVAwdQJMClASVBpYIlwyeDp0QCgKUDB9gVA4A09TV
1tfe3UQLApQMH2BUDgDT1NXW197dAAAAAAAAAAAA/Xu9qfZXAan0TwKp/QMAkRMBAJBoWkT5yAEA
tR8gA9VI9vdw9AMAqgAAgJL1AwEq4QMIqvYDAiqZAACU4QMVKuIDFiroAwCq4AMUqmhaBPkAAT/W
CAEAkABdBPn0T0Kp9ldBqf17w6jAA1/W/Xu9qfZXAan0TwKp/QMAkRMBAJBjYkT5wwEAtYj//5AI
CRCR9AMAqgAAgJL1AwEq4QMIqvYDAip+AACU4QMVKuIDFirjAwCq4AMUqmNiBPkIAQCQPwAKcQk8
gFIIXUT5QABJegQJQPrpB58awQAAVF+AB3HBAABUPwAUcYEAAFRoAAC0CAEAkAkhIzn0T0Kp9ldB
qf17w6hgAB/W/4MB0f17Aqn3GwD59lcEqfRPBan9gwCREwEAkGRqRPkEAgC1iP//kAiBD5H0AwCq
AACAkvUDAarhAwiq9gMCqvcDA6pUAACU4wMXquIDFqrhAxWq5AMAquADFKpkagT5CAEAkAghYzko
AgA2IwYAtGAAQP0IACYeH6EFcUsCAFQIPAwOH3EDcesBAFRoCEC5H9ECcYsBAFRoDEC5Hy0CcS0B
AFTgAx8qLAAAFPRPRan3G0D59ldEqf17Qqn/gwGRgAAf1oj//5CJ//+QA+YHbwG5Qf2I//+QIvXA
PQCcoQ5hBED940MAkSAEGG4B7cA9iP//kAGcoU4AhKJOIEQYbgHhwD2I//+QAsChTgHAoQ4AHCNO
IViCTiCEoE4B8cA9AUShTgEUIW/hB4A9CgAAFIj//5AIgQ6R4kMAkQABwD2I//+QCEEOkQEBwD3j
AwCR4QMArYAAP9b0T0Wp9xtA+fZXRKn9e0Kp/4MBkcADX9YAAAAA8Hu/qZAAAJARUkT5EIIikSAC
H9YfIAPVHyAD1R8gA9WQAACQEVZE+RCiIpEgAh/WDgAAAAAAAAA7AAAAAAAAAB4AAAAAAAAACAAA
AAAAAAD7//9vAAAAAAEAAAAAAAAAFwAAAAAAAABYAwAAAAAAAAIAAAAAAAAAGAAAAAAAAAADAAAA
AAAAAJAIAgAAAAAAFAAAAAAAAAAHAAAAAAAAAAYAAAAAAAAAOAIAAAAAAAALAAAAAAAAABgAAAAA
AAAABQAAAAAAAAAIAwAAAAAAAAoAAAAAAAAASgAAAAAAAAD1/v9vAAAAALACAAAAAAAABAAAAAAA
AADYAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACABwEAAAAA
AGNsYW5nIHZlcnNpb24gMjEuMS4wAExpbmtlcjogTExEIDIxLjEuMAAALmR5bnN5bQAuZ251Lmhh
c2gALmhhc2gALmR5bnN0cgAucmVsYS5wbHQALnJvZGF0YQAuZWhfZnJhbWVfaGRyAC5laF9mcmFt
ZQAudGV4dAAucGx0AC5keW5hbWljAC5nb3QucGx0AC5yZWxyb19wYWRkaW5nAC5ic3MALmNvbW1l
bnQALnNoc3RydGFiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAsAAAACAAAAAAAAADgCAAAAAAAAOAIAAAAAAAB4AAAA
AAAAAAQAAAABAAAACAAAAAAAAAAYAAAAAAAAAAkAAAD2//9vAgAAAAAAAACwAgAAAAAAALACAAAA
AAAAKAAAAAAAAAABAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAATAAAABQAAAAIAAAAAAAAA2AIAAAAA
AADYAgAAAAAAADAAAAAAAAAAAQAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAGQAAAAMAAAACAAAAAAAA
AAgDAAAAAAAACAMAAAAAAABKAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACEAAAAEAAAA
QgAAAAAAAABYAwAAAAAAAFgDAAAAAAAAGAAAAAAAAAABAAAADAAAAAgAAAAAAAAAGAAAAAAAAAAr
AAAAAQAAADIAAAAAAAAAcAMAAAAAAABwAwAAAAAAAKQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAA
AAAAAAAAMwAAAAEAAAACAAAAAAAAABQEAAAAAAAAFAQAAAAAAAAkAAAAAAAAAAAAAAAAAAAABAAA
AAAAAAAAAAAAAAAAAEEAAAABAAAAAgAAAAAAAAA4BAAAAAAAADgEAAAAAAAAzAAAAAAAAAAAAAAA
AAAAAAgAAAAAAAAAAAAAAAAAAABLAAAAAQAAAAYAAAAAAAAABAUBAAAAAAAEBQAAAAAAAHgCAAAA
AAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAUQAAAAEAAAAGAAAgAAAAAIAHAQAAAAAAgAcAAAAA
AAAwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAFYAAAAGAAAAAwAAAAAAAACwBwIAAAAA
ALAHAAAAAAAA4AAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAEAAAAAAAAABfAAAAAQAAAAMAAAAAAAAA
kAgCAAAAAACQCAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAaAAAAAgAAAAD
AAAAAAAAALAIAgAAAAAAsAgAAAAAAABQBwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHcA
AAAIAAAAAwAAAAAAAACwCAMAAAAAALAIAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAA
AAAAAAB8AAAAAQAAADAAAAAAAAAAAAAAAAAAAACwCAAAAAAAACgAAAAAAAAAAAAAAAAAAAABAAAA
AAAAAAEAAAAAAAAAhQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAA2AgAAAAAAACPAAAAAAAAAAAAAAAA
AAAAAQAAAAAAAAAAAAAAAAAAAA==
